### ISSUE TITLE
求sql文件

### ISSUE THREAD

**Issue by luoxia-wen** [lutgcy/-PSMS#1]
作者能求一份数据库文件吗

**Comment by sunflowerskyfive** [comment]
请问程序建立之后让输入的账号密码是什么啊

**Comment by sunflowerskyfive** [comment]
> 作者能求一份数据库文件吗



> 请问程序建立之后让输入的账号密码是什么啊

**Comment by sunflowerskyfive** [comment]
这个我知道了，程序建立后让输入的账号密码就是你建立的psms数据库中的admin表中存储的账号密码
